### ISSUE TITLE
Fel när jag använder webbappen i SV. Hittar inget i konsolen, tips på hur jag kan lösa detta?

### ISSUE THREAD

**Issue by Ninhow** [sitevision/create-sitevision-app#10]
![image](https://user-images.githubusercontent.com/25687079/107658962-f5c9e980-6c86-11eb-9bb3-00a48dcb7db5.png)

Det sker utan att jag gör någon ändring i boilerplate. Webbappen skapad med Npx.

**Comment by albinohrn** [comment]
Hej! Det ser ut att vara ett problem när man väljer att inte transpilera med [babel](https://babeljs.io/). Du kan fixa det genom att sätta `"transpile": true` i `package.json`.

```
"sitevision_scripts_properties": {
  "transpile": true
}
```

Då får du också möjlighet att använda nya JavaScript-features i din app som du inte skulle kunna göra annars. :)

**Comment by Ninhow** [comment]
Aha okej, tackar!

**Comment by Ninhow** [comment]
Hej, har kollat lite och det stämmer att det property löser det specifika error. Det blev ytterliggare problem i själva applikationen. Webbappen kunde inte läsa variabel som valdes i konfigurations fönstret. Variabel presenterades på sidan som [Object Object] och inte det faktiska värdet. Testade att göra en ny applikation och allt fungerade som det ska när jag vald transpile med Babel = true. Tack för hjälpen!

**Comment by albinohrn** [comment]
Skönt att det löste sig! Vi ska ta bort valet om transpilering för att minska förvirring i framtiden.
