### ISSUE TITLE
Operation is not allowed, feature 'addons' missing"

### ISSUE THREAD

**Issue by KevinFerm** [sitevision/create-sitevision-app#11]
Får detta när jag testar lokalt med `npm run create-addon`, användaren har behörighet till "Hantera Tillägg", så det borde inte vara några problem. Jag ser inte tillägg listas någonstans dock.
```
{
  "success": false,
  "type": "unknown",
  "description": "Unknown error occurred",
  "message": "EditModelHandlerValidationException: Operation is not allowed, feature 'addons' missing"
}
```

**Comment by albinohrn** [comment]
Hej,

enligt felmeddelandet saknar ni licens för att använda "Tillägg". Jag skulle ta kontakt med vår support för vidare frågor kring licensen. Du når dom på support@sitevision.se.

/Albin
