### ISSUE TITLE
NODE_TLS_REJECT_UNAUTHORIZED=0 npm run build force-deploy

### ISSUE THREAD

**Issue by heja1600** [sitevision/create-sitevision-app#6]
Adding NODE_TLS_REJECT_UNAUTHORIZED=0 to scripts under package.json like `"build": "NODE_TLS_REJECT_UNAUTHORIZED=0 sitevision-scripts build",`
gives following error:
`'NODE_TLS_REJECT_UNAUTHORIZED' is not recognized as an internal or external command,
operable program or batch file.`

Also by adding the prefix direcly in console gives the same error.

A quick fix to solve this issue is to add `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; `
to the files in node_modules:
* create-addon.js
* deploy.js
* deploy-prod.js

But this is ofcourse not a optimal since node_modules should be readonly and will be overwritten when someone else pulls the project.

The server is running over HTTPS. Is it any way around this? Or is it better to use the old boilderplate and manually add the lines to these files and overcome this issue

**Comment by albinohrn** [comment]
I would suggest you add `NODE_TLS_REJECT_UNAUTHORIZED=0` to the scripts in your `package.json`. 

```json
{
  ...
  "scripts": {
    "deploy": "NODE_TLS_REJECT_UNAUTHORIZED=0 sitevision-scripts deploy"
  }
}
```

**NOTE!** If you are running on Windows you will have to add [`cross-env`](https://www.npmjs.com/package/cross-env) as well.

**Comment by heja1600** [comment]
Okay thanks, im running windows thats the problem here :)
