### ISSUE TITLE
State lost of dynamically loaded config field

### ISSUE THREAD

**Issue by heja1600** [sitevision/create-sitevision-app#7]
The state of Dynamically loaded config fields is getting lost when the user re-enters the config window. The behavior im looking for here is that its still visible so the user doesnt have to re-enter all the information.

Loading fields dynamically in the config window is also brought up in the documentation so I assume this is something that should work, here the link to your documentation where you mention it: https://developer.sitevision.se/docs/webapps/configuration.

Here's the example you provided: 

`
//config/index.js
(function() {
   const router    = require('router');
   const requester = require('Requester');

   router.get('/', (req, res) => {
      requester
         .get('https://jsonplaceholder.typicode.com/posts')
         .done(data => res.render({ posts: data }));
   });
})();`

`// config/index.html
<div class="form-group">
	<label>Font</label>
	<select>
		<% _.each(posts, function(post) { %>
			<option value="<%- post.id %>">
				<%- post.title %>
			</option>
		<% }) %>
	</select>
</div>
`

Also, it would be great if you could encapsulate the storage for each webbapp instance, or atleast have the options for it. However this could be solvable without encapsulated storage, my idea was to add a extra id field to each entry giving each entry a namespace, and then let the user choose between these namespaces from a selectbox, and then based on their choice: dynamic loading of all the other config options based on the selected entry in the datastore.

But that involves caching or storage of these dynamically created fields. And the fields are dynamic, i cannot just hide them and then display them when i want to, thats not the behaviour im looking for.

**Comment by heja1600** [comment]
I have tried this with both server(your example)- client-side js, does not work

**Comment by albinohrn** [comment]
Hi! 👋 

Since this is not directly related to this project it's more related to the product SiteVision. Could you please send your question to our support. They're happy to help you at support@sitevision.se

/Albin
