### ISSUE TITLE
När kommer stöd för reactjs?

### ISSUE THREAD

**Issue by furuskog** [sitevision/create-sitevision-app#9]
Hej!
Det har pratats om en version för reactjs när kommer den? Hur har ni implementerat react? Kan man vara med och utvärdera? Då min arbetsgivare skulle ha nytta av detta.

**Comment by albinohrn** [comment]
Hej, React är något som vi håller på och utvärderar internt för tillfället och vi kan inte säga exakt när det kommer. Hör gärna av dig till mig på <förnamn>.<efternamn>@sitevision.se så kan jag förklara vidare!
